import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { projects, videos, frames, annotations } from '@/lib/db/schema';
import { eq, inArray } from 'drizzle-orm';
import fs from 'fs/promises';
import path from 'path';

const DATA_ROOT = process.env.DATA_ROOT || './.cvstudio';

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    const format = searchParams.get('format') || 'yolo';

    if (!projectId) {
      return NextResponse.json({ error: 'projectId is required' }, { status: 400 });
    }

    const projectRecord = await db.select().from(projects).where(eq(projects.id, projectId)).limit(1);
    if (!projectRecord.length) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const projectVideos = await db.select().from(videos).where(eq(videos.projectId, projectId));
    const videoIds = projectVideos.map((v) => v.id);

    let allFrames: any[] = [];
    let allAnnotations: any[] = [];

    if (videoIds.length > 0) {
      allFrames = await db.select().from(frames).where(inArray(frames.videoId, videoIds));
      const frameIds = allFrames.map((f) => f.id);
      if (frameIds.length > 0) {
        allAnnotations = await db.select().from(annotations).where(inArray(annotations.frameId, frameIds));
      }
    }

    // Read classes
    let classes: any[] = [];
    try {
      const classesFile = path.resolve(process.cwd(), DATA_ROOT, 'datasets', 'classes.json');
      const data = await fs.readFile(classesFile, 'utf8');
      classes = JSON.parse(data);
    } catch {
      classes = [{ name: 'Ball' }, { name: 'Player' }, { name: 'Racket' }];
    }

    const classNames = classes.map((c: any) => c.name);

    // Build YOLO data.yaml
    const yamlContent = `
# YOLOv8 / YOLOv11 Dataset Configuration
# Generated by CV Studio for project: ${projectRecord[0].name}
path: ${DATA_ROOT}/datasets
train: images/train
val: images/valid
test: images/test

# Classes (${classNames.length})
names:
${classNames.map((name: string, idx: number) => `  ${idx}: ${name}`).join('\n')}
`.trim();

    const exportDir = path.resolve(process.cwd(), DATA_ROOT, 'exports', projectId);
    await fs.mkdir(exportDir, { recursive: true });
    await fs.writeFile(path.join(exportDir, 'data.yaml'), yamlContent);

    return NextResponse.json({
      success: true,
      format,
      projectName: projectRecord[0].name,
      stats: {
        totalVideos: projectVideos.length,
        totalFrames: allFrames.length,
        totalAnnotations: allAnnotations.length,
        classesCount: classNames.length,
        classes: classNames,
      },
      yamlContent,
      exportPath: `exports/${projectId}/data.yaml`,
    });
  } catch (error) {
    console.error('Failed to generate export', error);
    return NextResponse.json({ error: 'Failed to generate export' }, { status: 500 });
  }
}
